name: Run defillama_arbitrum_tvl

on:
  schedule:
    - cron: "0 23 * * *"  # Runs every hour (modify as needed)
  workflow_dispatch:  # Allows manual trigger

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Set Environment Variables
        run: echo "DUNE_API_KEY=${{ secrets.DUNE_API_KEY }}" >> $GITHUB_ENV

      - name: Run all scripts
        run: |
          python defillama/defillama_aave.py
          sleep 20
          python defillama/defillama_gmx.py
          sleep 20
          python defillama/defillama_uniswap.py
          sleep 20
          python defillama/defillama_camelot.py
          sleep 20
          python defillama/defillama_compound.py
          sleep 20
          python defillama/defillama_defi_saver.py
          sleep 20
          python defillama/defillama_dolomite.py
          sleep 20
          python defillama/defillama_euler.py
          sleep 20
          python defillama/defillama_fluid.py
          sleep 20
          python defillama/defillama_franklin_templeton.py
          sleep 20
          python defillama/defillama_pendle.py
          sleep 20
          python defillama/defillama_spiko.py
          sleep 20
          python defillama/defillama_stables_labs_usdx.py
          sleep 20
          python defillama/defillama_stargate.py
